In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import glob
import cv2
import tensorflow as tf
import keras

from keras.models import Model, Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
#from keras.layers.normalization import BatchNormalization
#tf.keras.layers.BatchNormalization()
from tensorflow.keras.layers import BatchNormalization
import os
import seaborn as sns
from keras.applications.vgg16 import VGG16

In [2]:
print(os.listdir("C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/"))

['Test', 'Train']


In [3]:
SIZE = 224

In [4]:
train_images = []
train_labels = [] 

In [5]:
for directory_path in glob.glob("C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Train/*"):
    label = directory_path.split("\\")[-1]
    print(label)
    for img_path in glob.glob(os.path.join(directory_path, "*.jpg")):
        print(img_path)
        img = cv2.imread(img_path, cv2.IMREAD_COLOR)       
        img = cv2.resize(img, (SIZE, SIZE))
        img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
        train_images.append(img)
        train_labels.append(label)

without_mask
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Train\without_mask\download (1).jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Train\without_mask\download (2).jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Train\without_mask\download (3).jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Train\without_mask\download.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Train\without_mask\erge-mahindra-BCD0FN-bNNk-unsplash.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Train\without_mask\erge-mahindra-g8kvlk_EmGo-unsplash.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Train\without_mask\erge-mahindra-rFUpzPhqkE4-unsplash.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Train\without_mask\eva-franco-mask-denim-baseball-hat-with-american-flag-scarf-set-14033496047705_1600x.jpg
C:/Us

In [6]:
train_images = np.array(train_images)
train_labels = np.array(train_labels)

In [7]:
train_labels.shape

(2992,)

In [8]:
train_labels[2000]

'with_mask'

In [9]:
test_images = []
test_labels = [] 
for directory_path in glob.glob("C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Test/*"):
    label = directory_path.split("\\")[-1]
    print(label)
    for img_path in glob.glob(os.path.join(directory_path, "*.jpg")):
        print(img_path)
        img = cv2.imread(img_path, cv2.IMREAD_COLOR)
        img = cv2.resize(img, (SIZE, SIZE))
        img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
        test_images.append(img)
        test_labels.append(label)

without_mask
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Test\without_mask\Faceimg1,003.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Test\without_mask\Faceimg1,004.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Test\without_mask\Faceimg1,005.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Test\without_mask\Faceimg1,006.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Test\without_mask\Faceimg1,007.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Test\without_mask\Faceimg1,008.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Test\without_mask\Faceimg1,009.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Test\without_mask\Faceimg1,010.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop/summer project/mask folder/Test\without_mask\Faceimg1,011.jpg
C:/Users/DIBYAJYOTI HALOI/OneDrive/Desktop

In [10]:
test_images[0]

array([[[118,  87,  66],
        [121,  90,  69],
        [125,  94,  73],
        ...,
        [144, 107,  80],
        [149, 110,  83],
        [152, 112,  86]],

       [[121,  90,  69],
        [123,  92,  71],
        [126,  95,  74],
        ...,
        [140, 103,  77],
        [145, 108,  81],
        [149, 110,  84]],

       [[127,  96,  75],
        [128,  96,  75],
        [129,  98,  77],
        ...,
        [133,  97,  70],
        [139, 103,  76],
        [143, 107,  79]],

       ...,

       [[209, 149, 112],
        [210, 149, 113],
        [210, 150, 113],
        ...,
        [ 88,  56,  54],
        [ 88,  56,  56],
        [ 89,  56,  57]],

       [[207, 147, 110],
        [208, 148, 111],
        [209, 149, 112],
        ...,
        [ 89,  56,  54],
        [ 90,  57,  57],
        [ 91,  57,  58]],

       [[206, 146, 109],
        [207, 147, 110],
        [208, 148, 111],
        ...,
        [ 90,  56,  54],
        [ 91,  57,  57],
        [ 92,  58,  59]]

In [11]:
test_labels[0]

'without_mask'

In [12]:
test_images = np.array(test_images)
test_labels = np.array(test_labels)

In [13]:
test_labels

array(['without_mask', 'without_mask', 'without_mask', ..., 'with_mask',
       'with_mask', 'with_mask'], dtype='<U12')

In [14]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(test_labels)
test_labels_encoded = le.transform(test_labels)
le.fit(train_labels)
train_labels_encoded = le.transform(train_labels)

In [15]:
test_labels_encoded

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [16]:
x_train, y_train, x_test, y_test = train_images, train_labels_encoded, test_images, test_labels_encoded

In [17]:
x_train.shape

(2992, 224, 224, 3)

In [18]:
x_train=x_train/255.0

In [19]:
x_test=x_test/255.0

In [20]:
from keras.utils import to_categorical
y_train_one_hot = to_categorical(y_train)
y_test_one_hot = to_categorical(y_test)

In [21]:
y_train_one_hot[0]

array([0., 1.], dtype=float32)

In [22]:
y_train[0]

1

In [23]:
train_labels_encoded[0]

1

In [24]:
train_labels[0]

'without_mask'

In [25]:
from keras.models import Sequential

In [26]:
model=Sequential()

In [27]:
VGG_model = VGG16(weights='imagenet', include_top=True, input_shape=(SIZE, SIZE, 3))

In [28]:
for layer in VGG_model.layers:
	layer.trainable = False

In [29]:
model.add(VGG_model)

In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 vgg16 (Functional)          (None, 1000)              138357544 
                                                                 
Total params: 138,357,544
Trainable params: 0
Non-trainable params: 138,357,544
_________________________________________________________________


In [31]:
model.add(Dense(2,activation='softmax'))

In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 vgg16 (Functional)          (None, 1000)              138357544 
                                                                 
 dense (Dense)               (None, 2)                 2002      
                                                                 
Total params: 138,359,546
Trainable params: 2,002
Non-trainable params: 138,357,544
_________________________________________________________________


In [33]:
model.compile(optimizer=keras.optimizers.Adam(learning_rate= 1e-3),
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])

In [34]:
model.fit(x_train, y_train,epochs=3)

Epoch 1/3
94/94 [==============================] - 520s 5s/step - loss: 0.6900 - accuracy: 0.5294
Epoch 2/3
94/94 [==============================] - 587s 6s/step - loss: 0.6854 - accuracy: 0.5318
Epoch 3/3
94/94 [==============================] - 594s 6s/step - loss: 0.6815 - accuracy: 0.5398


In [35]:
y_predict=model.predict(x_test)

32/32 [==============================] - 200s 6s/step
